### ISSUE TITLE
Make colon, comma before arrays optional

### ISSUE THREAD

**Issue by noblepaul** [yonik/noggit#14]
```
{
"a"  [ 1,2,3]
}
```

is equivalent to

```
{
"a" : [ 1,2,3]
}
```

and 

```
{
"a":[ ["b"]["c"] ]
}
```

equivalent to

```
{
"a":[["b"],["c"] ]
}
```

**Comment by mikesterlingw** [comment]
According to the JSON standard the colon between the key and value is required, as is the comma separating values.

> An object structure is represented as a pair of curly brackets
   surrounding zero or more name/value pairs (or members).  A name is a
   string.  A single colon comes after each name, separating the name
   from the value. [1](http://www.ietf.org/rfc/rfc4627.txt)
>  A name is a string. A single colon comes after each name, separating the name from the value.[2](http://rfc7159.net/rfc7159#rfc.section.4)

Recommending this be closed as not an issue.
