### ISSUE TITLE
Make starting and ending braces optional

### ISSUE THREAD

**Issue by noblepaul** [yonik/noggit#7]
``` javascript
a: {key:val1},
b:{key:val2}
```

should be equivalent to 

``` javascript

{
a: {key:val1},
b:{key:val2}
}
```

**Comment by rmuller** [comment]
This is not valid JSON. So IMHO this issue should be closed as "not an issue".

**Comment by noblepaul** [comment]
A lot of what noggit does is not valid issue. We do  lot of these optional features so that users of the library can benefit
